/**
 * Canonical game content registry: deck pairs (faces, jokers, themes) and power metadata.
 * Behavior (apply/trigger) lives in `src/engine/powers/`.
 */
import {
  allJokersInDeckPair,
  deckPairs,
  DEFAULT_DECK_PAIR_ID,
  getDeckPairById,
  isDeckPairUnlocked,
  isDeckPairUnlockedById,
  jokerDefinitionForInGameId,
  maxJokersInPlayForDeckPair,
  type DeckFaceCard,
  type DeckFaceRank,
  type DeckInPair,
  type DeckJokerCard,
  type ThemedJokerInput,
  type DeckPairDefinition,
  type DeckPairId,
  type SuitTheme,
} from "@/content/deckPairs";
import {
  EFFECT_DEFINITIONS,
  EFFECT_SKIP1,
  EFFECT_SKIP2,
  EFFECT_TRANSPARENT,
  EFFECT_WILD,
  EFFECT_HALF_WILD,
} from "@/content/effectDefinitions";
import {
  getPowerDefinition,
  JOKER_POWER_2_KINGS_TRANSPARENT,
  JOKER_POWER_ALL_KINGS_TRANSPARENT,
  JOKER_POWER_CARD_SWAP,
  JOKER_POWER_FOUNDATION_RETURN,
  JOKER_POWER_SELECTED_CARD_HALFWILD,
  JOKER_POWER_SELECTED_CARD_SKIP1,
  JOKER_POWER_SELECTED_CARD_SKIP2,
  JOKER_POWER_SELECTED_CARD_TRANSPARENT,
  JOKER_POWER_SELECTED_CARD_WILD,
  JOKER_POWER_SELECTED_COLUMN_HALFWILD,
  JOKER_POWER_SELECTED_COLUMN_SKIP1,
  JOKER_POWER_SELECTED_COLUMN_SKIP2,
  JOKER_POWER_SELECTED_COLUMN_TRANSPARENT,
  JOKER_POWER_SELECTED_COLUMN_WILD,
  POWER_DEFINITIONS,
  powerHasTargetKind,
  powerTargetsDeckPopup,
  powerTargetsStockPopup,
  powerTargetsTableauColumn,
  powers,
  type PowerDefinition,
  type PowerTargetKind,
  type PowerTriggerClass,
} from "@/content/powerDefinitions";

export const GAME_CONTENT = {
  deckPairs,
  effectDefinitions: EFFECT_DEFINITIONS,
  powerDefinitions: POWER_DEFINITIONS,
} as const;

export type GameContent = typeof GAME_CONTENT;

export {
  allJokersInDeckPair,
  deckPairs,
  DEFAULT_DECK_PAIR_ID,
  getDeckPairById,
  isDeckPairUnlocked,
  isDeckPairUnlockedById,
  jokerDefinitionForInGameId,
  maxJokersInPlayForDeckPair,
  EFFECT_DEFINITIONS,
  EFFECT_SKIP1,
  EFFECT_SKIP2,
  EFFECT_TRANSPARENT,
  EFFECT_WILD,
  EFFECT_HALF_WILD,
  getPowerDefinition,
  JOKER_POWER_2_KINGS_TRANSPARENT,
  JOKER_POWER_ALL_KINGS_TRANSPARENT,
  JOKER_POWER_SELECTED_CARD_HALFWILD,
  JOKER_POWER_SELECTED_CARD_SKIP1,
  JOKER_POWER_SELECTED_CARD_SKIP2,
  JOKER_POWER_SELECTED_CARD_TRANSPARENT,
  JOKER_POWER_SELECTED_CARD_WILD,
  JOKER_POWER_SELECTED_COLUMN_HALFWILD,
  JOKER_POWER_SELECTED_COLUMN_SKIP1,
  JOKER_POWER_SELECTED_COLUMN_SKIP2,
  JOKER_POWER_SELECTED_COLUMN_TRANSPARENT,
  JOKER_POWER_SELECTED_COLUMN_WILD,
  JOKER_POWER_CARD_SWAP,
  JOKER_POWER_FOUNDATION_RETURN,
  POWER_DEFINITIONS,
  powerHasTargetKind,
  powerTargetsDeckPopup,
  powerTargetsStockPopup,
  powerTargetsTableauColumn,
  powers,
  type DeckFaceCard,
  type DeckFaceRank,
  type DeckInPair,
  type DeckJokerCard,
  type ThemedJokerInput,
  type DeckPairDefinition,
  type DeckPairId,
  type PowerDefinition,
  type PowerTargetKind,
  type PowerTriggerClass,
  type SuitTheme,
};
