/**
 * Shipped portrait basenames under `public/gameArt/portraits/<pairId>/deck{n}/`.
 * Keys: `${pairId}:${deckNum}:${suit}:${rank}` for courts; `${pairId}:${deckNum}:${1..4}` for jokers
 * (1 = red01 … 4 = black02). Display names match the art files.
 */
export const THEMED_COURT_PORTRAITS: Readonly<Record<string, { readonly file: string; readonly name: string }>> = {
  "computerScience:1:C:11": { file: "compSci01-jack-clubs-john-mccarthy.png", name: "John McCarthy" },
  "computerScience:1:C:12": { file: "compSci01-queen-clubs-grace-hopper.png", name: "Grace Hopper" },
  "computerScience:1:C:13": { file: "compSci01-king-clubs-alan-turing.png", name: "Alan Turing" },
  "computerScience:1:D:11": { file: "compSci01-jack-diamonds-whitfield-diffie.png", name: "Whitfield Diffie" },
  "computerScience:1:D:12": { file: "compSci01-queen-diamonds-hedy-lamarr.png", name: "Hedy Lamarr" },
  "computerScience:1:D:13": { file: "compSci01-king-diamonds-claude-shannon.png", name: "Claude Shannon" },
  "computerScience:1:H:11": { file: "compSci01-jack-hearts-douglas-engelbart.png", name: "Douglas Engelbart" },
  "computerScience:1:H:12": { file: "compSci01-queen-hearts-adele-goldberg.png", name: "Adele Goldberg" },
  "computerScience:1:H:13": { file: "compSci01-king-hearts-edsger-dijkstra.png", name: "Edsger W. Dijkstra" },
  "computerScience:1:S:11": { file: "compSci01-jack-spades-dennis-ritchie.png", name: "Dennis Ritchie" },
  "computerScience:1:S:12": { file: "compSci01-queen-spades-ada-lovelace.png", name: "Ada Lovelace" },
  "computerScience:1:S:13": { file: "compSci01-king-spades-john-von-neumann.png", name: "John von Neumann" },
  "computerScience:2:C:11": { file: "compSci02-jack-clubs-stephen-cook.png", name: "Stephen Cook" },
  "computerScience:2:C:12": { file: "compSci02-queen-clubs-shafi-goldwasser.png", name: "Shafi Goldwasser" },
  "computerScience:2:C:13": { file: "compSci02-king-clubs-donald-knuth.png", name: "Donald Knuth" },
  "computerScience:2:D:11": { file: "compSci02-jack-diamonds-john-osullivan.png", name: "John O'Sullivan" },
  "computerScience:2:D:12": { file: "compSci02-queen-diamonds-radia-perlman.png", name: "Radia Perlman" },
  "computerScience:2:D:13": { file: "compSci02-king-diamonds-vint-cerf.png", name: "Vint Cerf" },
  "computerScience:2:H:11": { file: "compSci02-jack-hearts-jimmy-wales.png", name: "Jimmy Wales" },
  "computerScience:2:H:12": { file: "compSci02-queen-hearts-margaret-hamilton.png", name: "Margaret Hamilton" },
  "computerScience:2:H:13": { file: "compSci02-king-hearts-tim-berners-lee.png", name: "Tim Berners-Lee" },
  "computerScience:2:S:11": { file: "compSci02-jack-spades-linus-torvalds.png", name: "Linus Torvalds" },
  "computerScience:2:S:12": { file: "compSci02-queen-spades-barbara-liskov.png", name: "Barbara Liskov" },
  "computerScience:2:S:13": { file: "compSci02-king-spades-ken-thompson.png", name: "Ken Thompson" },
  "mathematics:1:C:11": { file: "math01-jack-clubs-gottfried-wilhelm-leibniz.png", name: "Gottfried Wilhelm Leibniz" },
  "mathematics:1:C:12": { file: "math01-queen-clubs-sofia-kovalevskaya.png", name: "Sofya Kovalevskaya" },
  "mathematics:1:C:13": { file: "math01-king-clubs-euclid.png", name: "Euclid" },
  "mathematics:1:D:11": { file: "math01-jack-diamonds-joseph-louis-lagrange.png", name: "Joseph-Louis Lagrange" },
  "mathematics:1:D:12": { file: "math01-queen-diamonds-sophie-germain.png", name: "Sophie Germain" },
  "mathematics:1:D:13": { file: "math01-king-diamonds-carl-friedrich-gauss.png", name: "Carl Friedrich Gauss" },
  "mathematics:1:H:11": { file: "math01-jack-hearts-augustin-louis-cauchy.png", name: "Augustin-Louis Cauchy" },
  "mathematics:1:H:12": { file: "math01-queen-hearts-florence-nightingale.png", name: "Florence Nightingale" },
  "mathematics:1:H:13": { file: "math01-king-hearts-isaac-newton.png", name: "Isaac Newton" },
  "mathematics:1:S:11": { file: "math01-jack-spades-pierre-simon-laplace.png", name: "Pierre-Simon Laplace" },
  "mathematics:1:S:12": { file: "math01-queen-spades-mary-somerville.png", name: "Mary Somerville" },
  "mathematics:1:S:13": { file: "math01-king-spades-bernhard-riemann.png", name: "Bernhard Riemann" },
  "mathematics:2:C:11": { file: "math02-jack-clubs-alonzo-church.png", name: "Alonzo Church" },
  "mathematics:2:C:12": { file: "math02-queen-clubs-mary-cartwright.png", name: "Mary Cartwright" },
  "mathematics:2:C:13": { file: "math02-king-clubs-david-hilbert.png", name: "David Hilbert" },
  "mathematics:2:D:11": { file: "math02-jack-diamonds-g-h-hardy.png", name: "G. H. Hardy" },
  "mathematics:2:D:12": { file: "math02-queen-diamonds-emmy-noether.png", name: "Emmy Noether" },
  "mathematics:2:D:13": { file: "math02-king-diamonds-srinivasa-ramanujan.png", name: "Srinivasa Ramanujan" },
  "mathematics:2:H:11": { file: "math02-jack-hearts-andrey-kolmogorov.png", name: "Andrey Kolmogorov" },
  "mathematics:2:H:12": { file: "math02-queen-hearts-katherine-johnson.png", name: "Katherine Johnson" },
  "mathematics:2:H:13": { file: "math02-king-hearts-john-von-neumann.png", name: "John von Neumann" },
  "mathematics:2:S:11": { file: "math02-jack-spades-stephen-smale.png", name: "Stephen Smale" },
  "mathematics:2:S:12": { file: "math02-queen-spades-maryam-mirzakhani.png", name: "Maryam Mirzakhani" },
  "mathematics:2:S:13": { file: "math02-king-spades-henri-poincaré.png", name: "Henri Poincaré" },
  "westernPhilosophy:1:C:11": { file: "phil01-jack-clubs-plotinus.png", name: "Plotinus" },
  "westernPhilosophy:1:C:12": { file: "phil01-queen-clubs-hildegard-of-bingen.png", name: "Hildegard of Bingen" },
  "westernPhilosophy:1:C:13": { file: "phil01-king-clubs-aristotle.png", name: "Aristotle" },
  "westernPhilosophy:1:D:11": { file: "phil01-jack-diamonds-sextus-empiricus.png", name: "Sextus Empiricus" },
  "westernPhilosophy:1:D:12": { file: "phil01-queen-diamonds-hypatia-of-alexandria.png", name: "Hypatia of Alexandria" },
  "westernPhilosophy:1:D:13": { file: "phil01-king-diamonds-plato.png", name: "Plato" },
  "westernPhilosophy:1:H:11": { file: "phil01-jack-hearts-epicurus.png", name: "Epicurus" },
  "westernPhilosophy:1:H:12": { file: "phil01-queen-hearts-diotima-of-mantinea.png", name: "Diotima of Mantinea" },
  "westernPhilosophy:1:H:13": { file: "phil01-king-hearts-socrates.png", name: "Socrates" },
  "westernPhilosophy:1:S:11": { file: "phil01-jack-spades-augustine-of-hippo.png", name: "Augustine of Hippo" },
  "westernPhilosophy:1:S:12": { file: "phil01-queen-spades-aspasia-of-miletus.png", name: "Aspasia of Miletus" },
  "westernPhilosophy:1:S:13": { file: "phil01-king-spades-thomas-aquinas.png", name: "Thomas Aquinas" },
  "westernPhilosophy:2:C:11": { file: "phil02-jack-clubs-baruch-spinoza.png", name: "Baruch Spinoza" },
  "westernPhilosophy:2:C:12": { file: "phil02-queen-clubs-margaret-cavendish.png", name: "Margaret Cavendish" },
  "westernPhilosophy:2:C:13": { file: "phil02-king-clubs-rene-descartes.png", name: "René Descartes" },
  "westernPhilosophy:2:D:11": { file: "phil02-jack-diamonds-karl-popper.png", name: "Karl Popper" },
  "westernPhilosophy:2:D:12": { file: "phil02-queen-diamonds-emilie-du-chatelet.png", name: "Émilie du Châtelet" },
  "westernPhilosophy:2:D:13": { file: "phil02-king-diamonds-david-hume.png", name: "David Hume" },
  "westernPhilosophy:2:H:11": { file: "phil02-jack-hearts-philippa-foot.png", name: "Philippa Foot" },
  "westernPhilosophy:2:H:12": { file: "phil02-queen-hearts-simone-de-beauvoir.png", name: "Simone de Beauvoir" },
  "westernPhilosophy:2:H:13": { file: "phil02-king-hearts-immanuel-kant.png", name: "Immanuel Kant" },
  "westernPhilosophy:2:S:11": { file: "phil02-jack-spades-john-stuart-mill.png", name: "John Stuart Mill" },
  "westernPhilosophy:2:S:12": { file: "phil02-queen-spades-hannah-arendt.png", name: "Hannah Arendt" },
  "westernPhilosophy:2:S:13": { file: "phil02-king-spades-karl-marx.png", name: "Karl Marx" },
};

export const THEMED_JOKER_PORTRAITS: Readonly<Record<string, { readonly file: string; readonly name: string }>> = {
  "computerScience:1:1": { file: "compSci01-joker-red01-konrad-zuse.png", name: "Konrad Zuse" },
  "computerScience:1:2": { file: "compSci01-joker-red02-john-backus.png", name: "John Backus" },
  "computerScience:1:3": { file: "compSci01-joker-black01-charles-babbage.png", name: "Charles Babbage" },
  "computerScience:1:4": { file: "compSci01-joker-black02-norbert-wiener.png", name: "Norbert Wiener" },
  "computerScience:2:1": { file: "compSci02-joker-red01-geoffrey-hinton.png", name: "Geoffrey Hinton" },
  "computerScience:2:2": { file: "compSci02-joker-red02-guido-van-rossum.png", name: "Guido van Rossum" },
  "computerScience:2:3": { file: "compSci02-joker-black01-marvin-minsky.png", name: "Marvin Minsky" },
  "computerScience:2:4": { file: "compSci02-joker-black02-richard-stallman.png", name: "Richard Stallman" },
  "mathematics:1:1": { file: "math01-joker-red01-evariste-galois.png", name: "Évariste Galois" },
  "mathematics:1:2": { file: "math01-joker-red02-georg-cantor.png", name: "Georg Cantor" },
  "mathematics:1:3": { file: "math01-joker-black01-zeno-of-elea.png", name: "Zeno of Elea" },
  "mathematics:1:4": { file: "math01-joker-black02-pythagoras.png", name: "Pythagoras" },
  "mathematics:2:1": { file: "math02-joker-red01-paul-erdős.png", name: "Paul Erdős" },
  "mathematics:2:2": { file: "math02-joker-red02-benoit-mandelbrot.png", name: "Benoit Mandelbrot" },
  "mathematics:2:3": { file: "math02-joker-black01-kurt-gödel.png", name: "Kurt Gödel" },
  "mathematics:2:4": { file: "math02-joker-black02-stefan-banach.png", name: "Stefan Banach" },
  "westernPhilosophy:1:1": { file: "phil01-joker-red01-protagoras.png", name: "Protagoras" },
  "westernPhilosophy:1:2": { file: "phil01-joker-red02-pyrrho-of-elis.png", name: "Pyrrho of Elis" },
  "westernPhilosophy:1:3": { file: "phil01-joker-black01-diogenes-of-sinope.png", name: "Diogenes of Sinope" },
  "westernPhilosophy:1:4": { file: "phil01-joker-black02-heraclitus.png", name: "Heraclitus" },
  "westernPhilosophy:2:1": { file: "phil02-joker-red01-albert-camus.png", name: "Albert Camus" },
  "westernPhilosophy:2:2": { file: "phil02-joker-red02-jean-paul-sartre.png", name: "Jean-Paul Sartre" },
  "westernPhilosophy:2:3": { file: "phil02-joker-black01-friedrich-nietzsche.png", name: "Friedrich Nietzsche" },
  "westernPhilosophy:2:4": { file: "phil02-joker-black02-ludwig-wittgenstein.png", name: "Ludwig Wittgenstein" },
};
