/**
 * Shipped portrait basenames under `public/gameArt/portraits/<pairId>/deck{n}/` (WebP from
 * `pnpm run generate:portraits`). Masters in gitignored `art-source/portraits/` may use `.png`.
 * Keys: `${pairId}:${deckNum}:${suit}:${rank}` for courts; `${pairId}:${deckNum}:${1..4}` for jokers
 * (1 = red01 … 4 = black02). Display names match the art files.
 */
export const THEMED_COURT_PORTRAITS: Readonly<Record<string, { readonly file: string; readonly name: string }>> = {
  "computerScience:1:C:11": { file: "compSci01-jack-clubs-john-mccarthy.webp", name: "John McCarthy" },
  "computerScience:1:C:12": { file: "compSci01-queen-clubs-grace-hopper.webp", name: "Grace Hopper" },
  "computerScience:1:C:13": { file: "compSci01-king-clubs-alan-turing.webp", name: "Alan Turing" },
  "computerScience:1:D:11": { file: "compSci01-jack-diamonds-whitfield-diffie.webp", name: "Whitfield Diffie" },
  "computerScience:1:D:12": { file: "compSci01-queen-diamonds-hedy-lamarr.webp", name: "Hedy Lamarr" },
  "computerScience:1:D:13": { file: "compSci01-king-diamonds-claude-shannon.webp", name: "Claude Shannon" },
  "computerScience:1:H:11": { file: "compSci01-jack-hearts-douglas-engelbart.webp", name: "Douglas Engelbart" },
  "computerScience:1:H:12": { file: "compSci01-queen-hearts-adele-goldberg.webp", name: "Adele Goldberg" },
  "computerScience:1:H:13": { file: "compSci01-king-hearts-edsger-dijkstra.webp", name: "Edsger W. Dijkstra" },
  "computerScience:1:S:11": { file: "compSci01-jack-spades-dennis-ritchie.webp", name: "Dennis Ritchie" },
  "computerScience:1:S:12": { file: "compSci01-queen-spades-ada-lovelace.webp", name: "Ada Lovelace" },
  "computerScience:1:S:13": { file: "compSci01-king-spades-john-von-neumann.webp", name: "John von Neumann" },
  "computerScience:2:C:11": { file: "compSci02-jack-clubs-stephen-cook.webp", name: "Stephen Cook" },
  "computerScience:2:C:12": { file: "compSci02-queen-clubs-shafi-goldwasser.webp", name: "Shafi Goldwasser" },
  "computerScience:2:C:13": { file: "compSci02-king-clubs-donald-knuth.webp", name: "Donald Knuth" },
  "computerScience:2:D:11": { file: "compSci02-jack-diamonds-john-osullivan.webp", name: "John O'Sullivan" },
  "computerScience:2:D:12": { file: "compSci02-queen-diamonds-radia-perlman.webp", name: "Radia Perlman" },
  "computerScience:2:D:13": { file: "compSci02-king-diamonds-vint-cerf.webp", name: "Vint Cerf" },
  "computerScience:2:H:11": { file: "compSci02-jack-hearts-jimmy-wales.webp", name: "Jimmy Wales" },
  "computerScience:2:H:12": { file: "compSci02-queen-hearts-margaret-hamilton.webp", name: "Margaret Hamilton" },
  "computerScience:2:H:13": { file: "compSci02-king-hearts-tim-berners-lee.webp", name: "Tim Berners-Lee" },
  "computerScience:2:S:11": { file: "compSci02-jack-spades-linus-torvalds.webp", name: "Linus Torvalds" },
  "computerScience:2:S:12": { file: "compSci02-queen-spades-barbara-liskov.webp", name: "Barbara Liskov" },
  "computerScience:2:S:13": { file: "compSci02-king-spades-ken-thompson.webp", name: "Ken Thompson" },
  "mathematics:1:C:11": { file: "math01-jack-clubs-gottfried-wilhelm-leibniz.webp", name: "Gottfried Wilhelm Leibniz" },
  "mathematics:1:C:12": { file: "math01-queen-clubs-sofia-kovalevskaya.webp", name: "Sofya Kovalevskaya" },
  "mathematics:1:C:13": { file: "math01-king-clubs-euclid.webp", name: "Euclid" },
  "mathematics:1:D:11": { file: "math01-jack-diamonds-joseph-louis-lagrange.webp", name: "Joseph-Louis Lagrange" },
  "mathematics:1:D:12": { file: "math01-queen-diamonds-sophie-germain.webp", name: "Sophie Germain" },
  "mathematics:1:D:13": { file: "math01-king-diamonds-carl-friedrich-gauss.webp", name: "Carl Friedrich Gauss" },
  "mathematics:1:H:11": { file: "math01-jack-hearts-augustin-louis-cauchy.webp", name: "Augustin-Louis Cauchy" },
  "mathematics:1:H:12": { file: "math01-queen-hearts-florence-nightingale.webp", name: "Florence Nightingale" },
  "mathematics:1:H:13": { file: "math01-king-hearts-isaac-newton.webp", name: "Isaac Newton" },
  "mathematics:1:S:11": { file: "math01-jack-spades-pierre-simon-laplace.webp", name: "Pierre-Simon Laplace" },
  "mathematics:1:S:12": { file: "math01-queen-spades-mary-somerville.webp", name: "Mary Somerville" },
  "mathematics:1:S:13": { file: "math01-king-spades-bernhard-riemann.webp", name: "Bernhard Riemann" },
  "mathematics:2:C:11": { file: "math02-jack-clubs-alonzo-church.webp", name: "Alonzo Church" },
  "mathematics:2:C:12": { file: "math02-queen-clubs-mary-cartwright.webp", name: "Mary Cartwright" },
  "mathematics:2:C:13": { file: "math02-king-clubs-david-hilbert.webp", name: "David Hilbert" },
  "mathematics:2:D:11": { file: "math02-jack-diamonds-g-h-hardy.webp", name: "G. H. Hardy" },
  "mathematics:2:D:12": { file: "math02-queen-diamonds-emmy-noether.webp", name: "Emmy Noether" },
  "mathematics:2:D:13": { file: "math02-king-diamonds-srinivasa-ramanujan.webp", name: "Srinivasa Ramanujan" },
  "mathematics:2:H:11": { file: "math02-jack-hearts-andrey-kolmogorov.webp", name: "Andrey Kolmogorov" },
  "mathematics:2:H:12": { file: "math02-queen-hearts-katherine-johnson.webp", name: "Katherine Johnson" },
  "mathematics:2:H:13": { file: "math02-king-hearts-john-von-neumann.webp", name: "John von Neumann" },
  "mathematics:2:S:11": { file: "math02-jack-spades-stephen-smale.webp", name: "Stephen Smale" },
  "mathematics:2:S:12": { file: "math02-queen-spades-maryam-mirzakhani.webp", name: "Maryam Mirzakhani" },
  "mathematics:2:S:13": { file: "math02-king-spades-henri-poincaré.webp", name: "Henri Poincaré" },
  "westernPhilosophy:1:C:11": { file: "phil01-jack-clubs-plotinus.webp", name: "Plotinus" },
  "westernPhilosophy:1:C:12": { file: "phil01-queen-clubs-hildegard-of-bingen.webp", name: "Hildegard of Bingen" },
  "westernPhilosophy:1:C:13": { file: "phil01-king-clubs-aristotle.webp", name: "Aristotle" },
  "westernPhilosophy:1:D:11": { file: "phil01-jack-diamonds-sextus-empiricus.webp", name: "Sextus Empiricus" },
  "westernPhilosophy:1:D:12": { file: "phil01-queen-diamonds-hypatia-of-alexandria.webp", name: "Hypatia of Alexandria" },
  "westernPhilosophy:1:D:13": { file: "phil01-king-diamonds-plato.webp", name: "Plato" },
  "westernPhilosophy:1:H:11": { file: "phil01-jack-hearts-epicurus.webp", name: "Epicurus" },
  "westernPhilosophy:1:H:12": { file: "phil01-queen-hearts-diotima-of-mantinea.webp", name: "Diotima of Mantinea" },
  "westernPhilosophy:1:H:13": { file: "phil01-king-hearts-socrates.webp", name: "Socrates" },
  "westernPhilosophy:1:S:11": { file: "phil01-jack-spades-augustine-of-hippo.webp", name: "Augustine of Hippo" },
  "westernPhilosophy:1:S:12": { file: "phil01-queen-spades-aspasia-of-miletus.webp", name: "Aspasia of Miletus" },
  "westernPhilosophy:1:S:13": { file: "phil01-king-spades-thomas-aquinas.webp", name: "Thomas Aquinas" },
  "westernPhilosophy:2:C:11": { file: "phil02-jack-clubs-baruch-spinoza.webp", name: "Baruch Spinoza" },
  "westernPhilosophy:2:C:12": { file: "phil02-queen-clubs-margaret-cavendish.webp", name: "Margaret Cavendish" },
  "westernPhilosophy:2:C:13": { file: "phil02-king-clubs-rene-descartes.webp", name: "René Descartes" },
  "westernPhilosophy:2:D:11": { file: "phil02-jack-diamonds-karl-popper.webp", name: "Karl Popper" },
  "westernPhilosophy:2:D:12": { file: "phil02-queen-diamonds-emilie-du-chatelet.webp", name: "Émilie du Châtelet" },
  "westernPhilosophy:2:D:13": { file: "phil02-king-diamonds-david-hume.webp", name: "David Hume" },
  "westernPhilosophy:2:H:11": { file: "phil02-jack-hearts-philippa-foot.webp", name: "Philippa Foot" },
  "westernPhilosophy:2:H:12": { file: "phil02-queen-hearts-simone-de-beauvoir.webp", name: "Simone de Beauvoir" },
  "westernPhilosophy:2:H:13": { file: "phil02-king-hearts-immanuel-kant.webp", name: "Immanuel Kant" },
  "westernPhilosophy:2:S:11": { file: "phil02-jack-spades-john-stuart-mill.webp", name: "John Stuart Mill" },
  "westernPhilosophy:2:S:12": { file: "phil02-queen-spades-hannah-arendt.webp", name: "Hannah Arendt" },
  "westernPhilosophy:2:S:13": { file: "phil02-king-spades-karl-marx.webp", name: "Karl Marx" },
};

export const THEMED_JOKER_PORTRAITS: Readonly<Record<string, { readonly file: string; readonly name: string }>> = {
  "computerScience:1:1": { file: "compSci01-joker-red01-konrad-zuse.webp", name: "Konrad Zuse" },
  "computerScience:1:2": { file: "compSci01-joker-red02-john-backus.webp", name: "John Backus" },
  "computerScience:1:3": { file: "compSci01-joker-black01-charles-babbage.webp", name: "Charles Babbage" },
  "computerScience:1:4": { file: "compSci01-joker-black02-norbert-wiener.webp", name: "Norbert Wiener" },
  "computerScience:2:1": { file: "compSci02-joker-red01-geoffrey-hinton.webp", name: "Geoffrey Hinton" },
  "computerScience:2:2": { file: "compSci02-joker-red02-guido-van-rossum.webp", name: "Guido van Rossum" },
  "computerScience:2:3": { file: "compSci02-joker-black01-marvin-minsky.webp", name: "Marvin Minsky" },
  "computerScience:2:4": { file: "compSci02-joker-black02-richard-stallman.webp", name: "Richard Stallman" },
  "mathematics:1:1": { file: "math01-joker-red01-evariste-galois.webp", name: "Évariste Galois" },
  "mathematics:1:2": { file: "math01-joker-red02-georg-cantor.webp", name: "Georg Cantor" },
  "mathematics:1:3": { file: "math01-joker-black01-zeno-of-elea.webp", name: "Zeno of Elea" },
  "mathematics:1:4": { file: "math01-joker-black02-pythagoras.webp", name: "Pythagoras" },
  "mathematics:2:1": { file: "math02-joker-red01-paul-erdős.webp", name: "Paul Erdős" },
  "mathematics:2:2": { file: "math02-joker-red02-benoit-mandelbrot.webp", name: "Benoit Mandelbrot" },
  "mathematics:2:3": { file: "math02-joker-black01-kurt-gödel.webp", name: "Kurt Gödel" },
  "mathematics:2:4": { file: "math02-joker-black02-stefan-banach.webp", name: "Stefan Banach" },
  "westernPhilosophy:1:1": { file: "phil01-joker-red01-protagoras.webp", name: "Protagoras" },
  "westernPhilosophy:1:2": { file: "phil01-joker-red02-pyrrho-of-elis.webp", name: "Pyrrho of Elis" },
  "westernPhilosophy:1:3": { file: "phil01-joker-black01-diogenes-of-sinope.webp", name: "Diogenes of Sinope" },
  "westernPhilosophy:1:4": { file: "phil01-joker-black02-heraclitus.webp", name: "Heraclitus" },
  "westernPhilosophy:2:1": { file: "phil02-joker-red01-albert-camus.webp", name: "Albert Camus" },
  "westernPhilosophy:2:2": { file: "phil02-joker-red02-jean-paul-sartre.webp", name: "Jean-Paul Sartre" },
  "westernPhilosophy:2:3": { file: "phil02-joker-black01-friedrich-nietzsche.webp", name: "Friedrich Nietzsche" },
  "westernPhilosophy:2:4": { file: "phil02-joker-black02-ludwig-wittgenstein.webp", name: "Ludwig Wittgenstein" },
};
