/**
 * Shipped portrait basenames under `public/gameArt/portraits/<pairId>/deck{n}/` (WebP from
 * `pnpm run generate:portraits`). Masters in gitignored `art-source/portraits/` may use `.png`.
 * Keys: `${pairId}:${deckNum}:${suit}:${rank}` for courts; `${pairId}:${deckNum}:${1..4}` for jokers
 * (1 = red01 … 4 = black02). Display names live in `src/content/deckPairs/` (per face/joker).
 */
export const THEMED_COURT_PORTRAITS: Readonly<Record<string, { readonly file: string }>> = {
  "computerScience:1:C:11": { file: "compSci01-jack-clubs-john-mccarthy.webp" },
  "computerScience:1:C:12": { file: "compSci01-queen-clubs-grace-hopper.webp" },
  "computerScience:1:C:13": { file: "compSci01-king-clubs-alan-turing.webp" },
  "computerScience:1:D:11": { file: "compSci01-jack-diamonds-whitfield-diffie.webp" },
  "computerScience:1:D:12": { file: "compSci01-queen-diamonds-hedy-lamarr.webp" },
  "computerScience:1:D:13": { file: "compSci01-king-diamonds-claude-shannon.webp" },
  "computerScience:1:H:11": { file: "compSci01-jack-hearts-douglas-engelbart.webp" },
  "computerScience:1:H:12": { file: "compSci01-queen-hearts-adele-goldberg.webp" },
  "computerScience:1:H:13": { file: "compSci01-king-hearts-edsger-dijkstra.webp" },
  "computerScience:1:S:11": { file: "compSci01-jack-spades-dennis-ritchie.webp" },
  "computerScience:1:S:12": { file: "compSci01-queen-spades-ada-lovelace.webp" },
  "computerScience:1:S:13": { file: "compSci01-king-spades-john-von-neumann.webp" },
  "computerScience:2:C:11": { file: "compSci02-jack-clubs-stephen-cook.webp" },
  "computerScience:2:C:12": { file: "compSci02-queen-clubs-shafi-goldwasser.webp" },
  "computerScience:2:C:13": { file: "compSci02-king-clubs-donald-knuth.webp" },
  "computerScience:2:D:11": { file: "compSci02-jack-diamonds-john-osullivan.webp" },
  "computerScience:2:D:12": { file: "compSci02-queen-diamonds-radia-perlman.webp" },
  "computerScience:2:D:13": { file: "compSci02-king-diamonds-vint-cerf.webp" },
  "computerScience:2:H:11": { file: "compSci02-jack-hearts-jimmy-wales.webp" },
  "computerScience:2:H:12": { file: "compSci02-queen-hearts-margaret-hamilton.webp" },
  "computerScience:2:H:13": { file: "compSci02-king-hearts-tim-berners-lee.webp" },
  "computerScience:2:S:11": { file: "compSci02-jack-spades-linus-torvalds.webp" },
  "computerScience:2:S:12": { file: "compSci02-queen-spades-barbara-liskov.webp" },
  "computerScience:2:S:13": { file: "compSci02-king-spades-ken-thompson.webp" },
  "mathematics:1:C:11": { file: "math01-jack-clubs-gottfried-wilhelm-leibniz.webp" },
  "mathematics:1:C:12": { file: "math01-queen-clubs-sofia-kovalevskaya.webp" },
  "mathematics:1:C:13": { file: "math01-king-clubs-euclid.webp" },
  "mathematics:1:D:11": { file: "math01-jack-diamonds-joseph-louis-lagrange.webp" },
  "mathematics:1:D:12": { file: "math01-queen-diamonds-sophie-germain.webp" },
  "mathematics:1:D:13": { file: "math01-king-diamonds-carl-friedrich-gauss.webp" },
  "mathematics:1:H:11": { file: "math01-jack-hearts-augustin-louis-cauchy.webp" },
  "mathematics:1:H:12": { file: "math01-queen-hearts-florence-nightingale.webp" },
  "mathematics:1:H:13": { file: "math01-king-hearts-isaac-newton.webp" },
  "mathematics:1:S:11": { file: "math01-jack-spades-pierre-simon-laplace.webp" },
  "mathematics:1:S:12": { file: "math01-queen-spades-mary-somerville.webp" },
  "mathematics:1:S:13": { file: "math01-king-spades-bernhard-riemann.webp" },
  "mathematics:2:C:11": { file: "math02-jack-clubs-alonzo-church.webp" },
  "mathematics:2:C:12": { file: "math02-queen-clubs-mary-cartwright.webp" },
  "mathematics:2:C:13": { file: "math02-king-clubs-david-hilbert.webp" },
  "mathematics:2:D:11": { file: "math02-jack-diamonds-g-h-hardy.webp" },
  "mathematics:2:D:12": { file: "math02-queen-diamonds-emmy-noether.webp" },
  "mathematics:2:D:13": { file: "math02-king-diamonds-srinivasa-ramanujan.webp" },
  "mathematics:2:H:11": { file: "math02-jack-hearts-andrey-kolmogorov.webp" },
  "mathematics:2:H:12": { file: "math02-queen-hearts-katherine-johnson.webp" },
  "mathematics:2:H:13": { file: "math02-king-hearts-john-von-neumann.webp" },
  "mathematics:2:S:11": { file: "math02-jack-spades-stephen-smale.webp" },
  "mathematics:2:S:12": { file: "math02-queen-spades-maryam-mirzakhani.webp" },
  "mathematics:2:S:13": { file: "math02-king-spades-henri-poincaré.webp" },
  "westernPhilosophy:1:C:11": { file: "phil01-jack-clubs-plotinus.webp" },
  "westernPhilosophy:1:C:12": { file: "phil01-queen-clubs-hildegard-of-bingen.webp" },
  "westernPhilosophy:1:C:13": { file: "phil01-king-clubs-aristotle.webp" },
  "westernPhilosophy:1:D:11": { file: "phil01-jack-diamonds-sextus-empiricus.webp" },
  "westernPhilosophy:1:D:12": { file: "phil01-queen-diamonds-hypatia-of-alexandria.webp" },
  "westernPhilosophy:1:D:13": { file: "phil01-king-diamonds-plato.webp" },
  "westernPhilosophy:1:H:11": { file: "phil01-jack-hearts-epicurus.webp" },
  "westernPhilosophy:1:H:12": { file: "phil01-queen-hearts-diotima-of-mantinea.webp" },
  "westernPhilosophy:1:H:13": { file: "phil01-king-hearts-socrates.webp" },
  "westernPhilosophy:1:S:11": { file: "phil01-jack-spades-augustine-of-hippo.webp" },
  "westernPhilosophy:1:S:12": { file: "phil01-queen-spades-aspasia-of-miletus.webp" },
  "westernPhilosophy:1:S:13": { file: "phil01-king-spades-thomas-aquinas.webp" },
  "westernPhilosophy:2:C:11": { file: "phil02-jack-clubs-baruch-spinoza.webp" },
  "westernPhilosophy:2:C:12": { file: "phil02-queen-clubs-margaret-cavendish.webp" },
  "westernPhilosophy:2:C:13": { file: "phil02-king-clubs-rene-descartes.webp" },
  "westernPhilosophy:2:D:11": { file: "phil02-jack-diamonds-karl-popper.webp" },
  "westernPhilosophy:2:D:12": { file: "phil02-queen-diamonds-emilie-du-chatelet.webp" },
  "westernPhilosophy:2:D:13": { file: "phil02-king-diamonds-david-hume.webp" },
  "westernPhilosophy:2:H:11": { file: "phil02-jack-hearts-philippa-foot.webp" },
  "westernPhilosophy:2:H:12": { file: "phil02-queen-hearts-simone-de-beauvoir.webp" },
  "westernPhilosophy:2:H:13": { file: "phil02-king-hearts-immanuel-kant.webp" },
  "westernPhilosophy:2:S:11": { file: "phil02-jack-spades-john-stuart-mill.webp" },
  "westernPhilosophy:2:S:12": { file: "phil02-queen-spades-hannah-arendt.webp" },
  "westernPhilosophy:2:S:13": { file: "phil02-king-spades-karl-marx.webp" },
};

export const THEMED_JOKER_PORTRAITS: Readonly<Record<string, { readonly file: string }>> = {
  "computerScience:1:1": { file: "compSci01-joker-red01-konrad-zuse.webp" },
  "computerScience:1:2": { file: "compSci01-joker-red02-john-backus.webp" },
  "computerScience:1:3": { file: "compSci01-joker-black01-charles-babbage.webp" },
  "computerScience:1:4": { file: "compSci01-joker-black02-norbert-wiener.webp" },
  "computerScience:2:1": { file: "compSci02-joker-red01-geoffrey-hinton.webp" },
  "computerScience:2:2": { file: "compSci02-joker-red02-guido-van-rossum.webp" },
  "computerScience:2:3": { file: "compSci02-joker-black01-marvin-minsky.webp" },
  "computerScience:2:4": { file: "compSci02-joker-black02-richard-stallman.webp" },
  "mathematics:1:1": { file: "math01-joker-red01-evariste-galois.webp" },
  "mathematics:1:2": { file: "math01-joker-red02-georg-cantor.webp" },
  "mathematics:1:3": { file: "math01-joker-black01-zeno-of-elea.webp" },
  "mathematics:1:4": { file: "math01-joker-black02-pythagoras.webp" },
  "mathematics:2:1": { file: "math02-joker-red01-paul-erdős.webp" },
  "mathematics:2:2": { file: "math02-joker-red02-benoit-mandelbrot.webp" },
  "mathematics:2:3": { file: "math02-joker-black01-kurt-gödel.webp" },
  "mathematics:2:4": { file: "math02-joker-black02-stefan-banach.webp" },
  "westernPhilosophy:1:1": { file: "phil01-joker-red01-protagoras.webp" },
  "westernPhilosophy:1:2": { file: "phil01-joker-red02-pyrrho-of-elis.webp" },
  "westernPhilosophy:1:3": { file: "phil01-joker-black01-diogenes-of-sinope.webp" },
  "westernPhilosophy:1:4": { file: "phil01-joker-black02-heraclitus.webp" },
  "westernPhilosophy:2:1": { file: "phil02-joker-red01-albert-camus.webp" },
  "westernPhilosophy:2:2": { file: "phil02-joker-red02-jean-paul-sartre.webp" },
  "westernPhilosophy:2:3": { file: "phil02-joker-black01-friedrich-nietzsche.webp" },
  "westernPhilosophy:2:4": { file: "phil02-joker-black02-ludwig-wittgenstein.webp" },
};
